name: Deploy-TestAll2TO6

on:

  workflow_dispatch:

  schedule:

    - cron: '0 9 * * *' # every day at 6:00 am Argentina time (09:00 am UTC)

jobs:

  Run_Bot:

    runs-on: ubuntu-latest

    

    timeout-minutes: 59 # Limit the time of the bot

    

    env:

      ACCOUNTS: KEYS2 KEYS3

    

    steps:

      - uses: actions/checkout@v3.5.2

      - name: Set up Python

        uses: actions/setup-python@v4.6.0

        with:

          python-version: '3.x'

      - name: Install required packages

        run: |

          sudo apt-get update

          sudo apt-get install -y xvfb

          pip install -r requirements.txt

      - name: Run Script for all accounts

        run: |

          for account in $ACCOUNTS; do

            python MicrosoftRewardsBot.py --accounts ${{ secrets.$account }} --headless --fast --discord ${{ secrets.webhook }} --privacy &

            sleep 2

          done

          wait
